services:
    backend:
        # 현재 디렉토리(.)에 있는 방금 만든 Spring Boot Dockerfile을 사용해 빌드
        build: .
        container_name: bottabot_backend
        env_file: .env
        environment:
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_URL=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
            - REDIS_PASSWORD=${REDIS_PASSWORD}
            - REDIS_URL=${REDIS_URL}

        # 호스트 8080 : 컨테이너 8080 (스프링 부트 기본 포트)
        ports:
            - "8080:8080"

        # (주의) 로컬 코드를 덮어씌우는 파이썬식 볼륨 바인딩은 컴파일 언어인 자바와 충돌하므로 제거했습니다.
        restart: always
