spring:
  application:
    name: BottaBotBackend

  # 1. PostgreSQL 데이터소스 설정
  datasource:
    # 도커 네트워크 내부에서는 서비스 이름(예: postgres)으로 접근해야 합니다.
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  # 2. JPA / Hibernate 설정
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  # 3. Redis 설정
  data:
    redis:
      url: ${REDIS_URL}
      password: ${REDIS_PASSWORD}
